version: '3.3'
services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: 
      - /var/lib/postgresql/data
    expose:
      - 5432
  web:
    container_name: backend
    build: .
    command: >
      sh -c "yarn
      && yarn build
      && yarn start"
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - '80:3333'
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env
